# 1. Getting Started with Python.

In [4]:
import sys
# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, Shamir!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, Shamir!
Python version: 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]


## 1.1 Data Types in Python.

Mutable Data Types:Mutable objects can be changed after they are created. This means you can
modify their contents, such as adding or removing items, or changing their values without creating a
new object. For example - list

Immutable Data Types:Immutable objects cannot be changed once they are created. Any operation
that seems to modify an immutable object will actually create a new object instead of changing the
original.For example - tuple

In [8]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

# Trying to modify the tuple (will raise an error)
my_tuple.append(4) # this will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


AttributeError: 'tuple' object has no attribute 'append'

### 1.1.1 Some Common Data Types in Python:

#### Numeric:

These data types are used to represent numerical values.
    
• int: Represents integer values (e.g., 10, -3).

• float: Represents floating-point (decimal) values (e.g., 10.5, -2.7).

• complex: Represents complex numbers (e.g., 3 + 4j).

In [11]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


#### Sequence:

These data types are ordered collections of items. You can access elements by their position (index).

• str: string (str) represents sequence of characters enclosed by double quotes or single quotes.

(e.g., “Hello, World!”).It is an immutable sequence.

In [12]:
name = "Shamir"
greeting = 'Hello'
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: S
The last letter of the name is: r
The second letter to the fourth of the name is: ham
The first two letters of the name are: Sh
Substring starting from the third letter is: amir


• list: Represents lists, which can contain mixed data types and are mutable (e.g., ["apple",
"banana"]).

In [14]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list[1] = "Shamir"
mixed_list

[False, 'Shamir', True]

• tuple: Represents tuples, which are ordered and immutable collections (e.g., (1, 2, 3)).

In [19]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])
colors[0] = 'purple'
colors # will generate an error as tuple is immutable.

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


TypeError: 'tuple' object does not support item assignment

#### Mapping:

This category includes data types that store key-value pairs, allowing for efficient retrieval based on
keys.

• dict: Represents dictionaries, which can store various data types as values associated with unique
keys (e.g., "name": "Alice", "age": 25).

In [21]:
person = {'name':'Shamir','age':20,'city':'Kathmandu'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is Shamir. I am 20 years old and I live at Kathmandu.
All keys: ['name', 'age', 'city']
All values: ['Shamir', 20, 'Kathmandu']


#### Set:

Sets are unordered collections of unique elements. They are useful for membership testing and elimi-
nating duplicate entries.

• set: A mutable collection of unique items (e.g., 1, 2, 3).

• frozenset: An immutable version of a set (e.g., frozenset([1, 2, 3])).

A frozenset in Python is an immutable and hashable version of a standard set. Like a regular set, it is an unordered collection of unique elements; the key difference is that its contents cannot be modified after creation.

In [24]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

frozenset([3,4,5])

{1, 2, 3, 4, 5}


frozenset({3, 4, 5})

#### Boolean:

This category contains types that represent truth values.
    
• bool: Represents boolean values (True or False).

In [25]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


#### Special:

This category is used for unique data types that do not fit into the other categories.
                     
• NoneType: Represents the absence of a value or a null value (e.g., None).

In [26]:
result = None

## 1.2 Logical Statements and Loops.

Python code can be decomposed into packages, modules, statements, and expressions, as follows:

1. Expressions create and process objects:

• Expressions are part of statements that return a value, such as variables, operators, or function
calls.

2. Statements contain expressions:

• Statements are sections of code that perform an action. The main groups of Python state-
ments are: assignment statements, print statements, conditional statements (if, break, con-
tinue, try), and looping statements (for, while).

3. Module Contain statements:

• Modules are Python files that contain Python statements, and are also called scripts.
    
4. Packages are composed of modules:

• Packages are Python programs that collect related modules together within a single directory
hierarchy.

## 1.3 Logical Statements:

Logical statements are used to perform conditional operations. The primary logical statements in Python
are:

• if: Executes a block of code if the condition is true.
    
if condition:

Code to execute if condition is true

• elif: Short for ”else if,” allows for multiple conditions to be checked sequentially.
                                   
if condition1:

Code for condition1
elif condition2:

Code for condition2

• else: Executes a block of code if none of the preceding conditions are true.
                                   
if condition:

Code if condition is true

else:

Code if condition is false

In [29]:
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


• Comparison operators: Used to compare values.
    
– ==: Equal to

– !=: Not equal to

– <: Less than

– >: Greater than

– <=: Less than or equal to

– >=: Greater than or equal to

In [31]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


• Logical operators: Used to combine multiple conditions.

– and: True if both conditions are true.

– or: True if at least one condition is true.

– not: Inverts the truth value of the condition.

In [32]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
    print("At least one of a or b is True") # This will be printed
else:
    print("Both a and b are False")
# Using the ’not’ operator
if not a:
    print("a is False") # This will not be printed
else:
    print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


### 1.3.1 Loops:
Loops are used to execute a block of code multiple times. The primary loop types in Python are:

• for loop: Iterates over a sequence (like a list, tuple, or string).

for item in iterable:

Code to execute for each item

• while loop: Repeats as long as a condition is true.

while condition:

Code to execute while condition is true

• break: Exits the loop immediately.

for item in iterable:

if some_condition:

break # Exit loop

• continue: Skips the current iteration and continues with the next iteration of the loop.

for item in iterable:

if some_condition:

continue # Skip to the next iteration

In [34]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
    print(fruit)
# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break
# Continiue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


## 1.4 Functions.

### 1.4.1 Built - in - Functions:

Python provides a wide range of built-in functions that are ready to use. These functions perform
common tasks and are available without the need to import additional modules.Presented below is an
example showcase; for more details, refer to the Python Reference on W3Schools

In [37]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
print(length)
data_type = type(42) # Output: <class ’int’>
print(data_type)
total = sum([1, 2, 3]) # Output: 6
print(total)

Hello, World!
5
<class 'int'>
6


### 1.4.2 Built - in - Methods:

In [39]:
# str.upper(): Converts all characters in a string to uppercase.
message = "Shamir".upper() 
print(message)
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
print(fruits)
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25
print(age)

SHAMIR
['apple', 'banana', 'cherry']
25


### 1.4.3 User - Defined - Function:

In [50]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius) and then asks for the temperature value. It calculates and returns
    the converted temperature.
    Returns:
        float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")

    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")

    if choice == "1":
        # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit

    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius

    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None

# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius


Enter 1 or 2:  1
Enter temperature in Celsius:  23


23.0C is equal to 73.4F


73.4

## 1.5 Global and Local Variables:

1. Global Variables:

A global variable is defined outside of any function and is accessible from any part of the program,
including within functions. Global variables maintain their values throughout the program’s execution
and can be accessed or modified by any function unless explicitly declared as nonlocal or redefined
within the function.

In [52]:
x = 10 # Global Variable.
def print_global():
    print(x) # Accessing global variable
print_global() # Output: 10

10


2. Local Variables:

A local variable is defined within a function and can only be accessed within that function. It exists
only during the function’s execution, and once the function completes, the local variable is removed
from memory.

In [59]:
def print_local():
    y = 5 # Local variable
    print(y)
print_local() # Output: 5
print(y)

5
10


3. Accessing and Modifying Global Variables Inside a Function

To modify a global variable within a function, we must use the global keyword. Otherwise, assigning
a new value to a global variable within a function will create a new local variable with the same name,
leaving the global variable unchanged.

In [61]:
x = 10 # Global variable
def modify_global():
    global x # Declaring x as global
    x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


# 2. TO - DO - Task

## 2.1 Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.
    
• The program should:

1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2. Ask the user to input the value to be converted.
    
3. Perform the conversion and display the result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

3. User Input: Prompt the user to select the conversion type and input the value.

4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.


• Conversion Options:

1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).

2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L).

In [24]:
def length_conversion():
    """
    Converts length between feet and meters.

    Prompts the user to select a conversion direction:
        - 'm': Converts feet to meters (feet × 0.3048)
        - 'f': Converts meters to feet (meters ÷ 0.3048)

    Parameters:
        None — all input is collected interactively via input().

    Returns:
        float: The converted length value, or None if input is invalid.
    """
    try:
        length_input = input("Type 'm' to convert feet → meters, or 'f' to convert meters → feet: ")
        length_input = length_input.lower().strip()

        if length_input == "m":
            f_input = float(input("Enter the value in feet: "))
            meter = f_input * 0.3048
            return meter
        elif length_input == "f":
            m_input = float(input("Enter the value in meters: "))
            feet = m_input / 0.3048
            return feet
        else:
            print("Invalid input. Please type 'm' or 'f'.")
            return None
    except ValueError:
        print("Invalid number entered. Please try again.")
        return None


def weight_conversion():
    """
    Converts weight between pounds and kilograms.

    Prompts the user to select a conversion direction:
        - 'kg' : Converts pounds to kilograms (pounds ÷ 2.205)
        - 'lbs': Converts kilograms to pounds (kilograms × 2.205)

    Parameters:
        None — all input is collected interactively via input().

    Returns:
        float: The converted weight value, or None if input is invalid.
    """
    try:
        weight_input = input("Type 'kg' to convert pounds → kilograms, or 'lbs' to convert kilograms → pounds: ")
        weight_input = weight_input.lower().strip()

        if weight_input == "kg":
            lbs_input = float(input("Enter the value in pounds: "))
            kilogram = lbs_input / 2.205
            return kilogram
        elif weight_input == "lbs":
            kg_input = float(input("Enter the value in kilograms: "))
            lbs = kg_input * 2.205
            return lbs
        else:
            print("Invalid input. Please type 'kg' or 'lbs'.")
            return None
    except ValueError:
        print("Invalid number entered. Please try again.")
        return None


def volume_conversion():
    """
    Converts volume between gallons and liters.

    Prompts the user to select a conversion direction:
        - 'l'  : Converts gallons to liters (gallons × 3.78541)
        - 'gal': Converts liters to gallons (liters ÷ 3.78541)

    Parameters:
        None — all input is collected interactively via input().

    Returns:
        float: The converted volume value, or None if input is invalid.
    """
    try:
        vol_input = input("Type 'l' to convert gallons → liters, or 'gal' to convert liters → gallons: ")
        vol_input = vol_input.lower().strip()

        if vol_input == "l":
            gal_input = float(input("Enter the value in gallons: "))
            liter = gal_input * 3.78541
            return liter
        elif vol_input == "gal":
            l_input = float(input("Enter the value in liters: "))
            gallon = l_input / 3.78541
            return gallon
        else:
            print("Invalid input. Please type 'l' or 'gal'.")
            return None
    except ValueError:
        print("Invalid number entered. Please try again.")
        return None

while True:
    user_input = input("Enter the type of conversion (l for length, w for weight and v for volumn or q to quit)")

    user_input = user_input.lower().strip()

    if user_input == "l":
        result = length_conversion()
        if result is not None:
            print(f"Result: {result:.4f}")

    elif user_input == "w":
        result = weight_conversion()
        if result is not None:
            print(f"Result: {result:.4f}")

    elif user_input == "v":
        result = volume_conversion()
        if result is not None:
            print(f"Result: {result:.4f}")

    elif user_input == "q":
        print("Program ended.")
        break
    else:
        print("Invalid conversion enter l for length, w for weight and v for volumn or q to quit")




Enter the type of conversion (l for length, w for weight and v for volumn or q to quit) dwr


Invalid conversion enter l for length, w for weight and v for volumn or q to quit


Enter the type of conversion (l for length, w for weight and v for volumn or q to quit) l
Type 'm' to convert feet → meters, or 'f' to convert meters → feet:  m
Enter the value in feet:  safdsa


Invalid number entered. Please try again.


Enter the type of conversion (l for length, w for weight and v for volumn or q to quit) l
Type 'm' to convert feet → meters, or 'f' to convert meters → feet:  m
Enter the value in feet:  546


Result: 166.4208


Enter the type of conversion (l for length, w for weight and v for volumn or q to quit) q


Program ended.


Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.
    
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.
                                                                  
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.                                       

In [25]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list of float): A non-empty list of numeric values.

    Returns:
        float: The total sum of all numbers in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot calculate sum of an empty list.")
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average (mean) of a list of numbers.

    Parameters:
        numbers (list of float): A non-empty list of numeric values.

    Returns:
        float: The arithmetic mean of the numbers in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)


def calculate_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list of float): A non-empty list of numeric values.

    Returns:
        float: The largest number in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)


def calculate_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list of float): A non-empty list of numeric values.

    Returns:
        float: The smallest number in the list.

    Raises:
        ValueError: If the list is empty.
    """
    if not numbers:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)


def get_numbers():
    """
    Prompts the user to enter a list of numbers separated by spaces,
    and parses them into a list of floats.

    Parameters:
        None — input is collected interactively via input().

    Returns:
        list of float: A list of parsed numeric values.

    Raises:
        ValueError: If any entered value is non-numeric or the input is empty.
    """
    raw = input("Enter numbers separated by spaces: ").strip()
    if not raw:
        raise ValueError("No numbers were entered. Please provide at least one number.")
    return [float(n) for n in raw.split()]



OPERATIONS = {
    "1": ("Sum",     calculate_sum),
    "2": ("Average", calculate_average),
    "3": ("Maximum", calculate_maximum),
    "4": ("Minimum", calculate_minimum),
}

while True:
    print("\nSelect an operation:")
    for key, (name, _) in OPERATIONS.items():
        print(f"  {key}. {name}")
    print("  q. Quit")

    choice = input("\nEnter your choice: ").strip().lower()

    if choice == "q":
        print("Program ended.")
        break

    if choice not in OPERATIONS:
        print("Invalid choice. Please enter 1, 2, 3, 4, or q.")
        continue

    operation_name, operation_func = OPERATIONS[choice]

    try:
        numbers = get_numbers()
        result = operation_func(numbers)
        print(f"\n{operation_name} of {numbers} = {result:.4f}")

    except ValueError as e:
        print(f"Input error: {e}")


Select an operation:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum
  q. Quit



Enter your choice:  1
Enter numbers separated by spaces:  sars


Input error: could not convert string to float: 'sars'

Select an operation:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum
  q. Quit



Enter your choice:  1
Enter numbers separated by spaces:  2



Sum of [2.0] = 2.0000

Select an operation:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum
  q. Quit



Enter your choice:  1
Enter numbers separated by spaces:  2 3



Sum of [2.0, 3.0] = 5.0000

Select an operation:
  1. Sum
  2. Average
  3. Maximum
  4. Minimum
  q. Quit



Enter your choice:  q


Program ended. Goodbye!


## 2.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.
    
• Requirements:
    
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [4]:
def extract_every_other(lst):
    # new_lst = []
    # for i in range(0, len(lst), 2):
    #     new_lst.append(lst[i])
    # return new_lst
    new_lst = lst[::2]
    return new_lst


lst = [1,2,3,4,5,6]
new_lst = extract_every_other(lst)
print(new_lst)

    

[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
    
• Requirements:
    
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [31]:
def sublist(lst, start, end):
    new_lst = lst[start:end+1]
    return new_lst

lst = [1,2,3,4,5,6]
start = 2
end =4

new_lst = sublist(lst, start,end)
print(new_lst)

[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.
    
• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [42]:
def reverse_list(lst):
    new_lst = lst[::-1]
    return new_lst

lst = [1,2,3,4,5]
new_lst = reverse_list(lst)
print(new_lst)

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
    
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [47]:
def remove_first_last(lst):
    new_lst = lst[1:-1]
    return new_lst

lst=[1,2,3,4,5]
new_lst = remove_first_last(lst)
print(new_lst)

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
    
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [53]:
def first_n(lst, n):
    new_lst = lst[0:n]
    return new_lst

lst =[1,2,3,4,5]
new_lst = first_n(lst, 3)
print(new_lst)

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.
    
• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [66]:
def get_last_n(lst,n):
    new_lst = lst[-n:]
    return new_lst

lst = [1,2,3,4,5]
new_lst = get_last_n(lst,2)
print(new_lst)

[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
    
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [67]:
def reverse_skip(lst):
    new_lst = lst[::-2]
    return new_lst

lst = [1,2,3,4,5]
new_lst = reverse_skip(lst)
print(new_lst)

[5, 3, 1]


## 2.3 Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
    
• Requirements:
    
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
    
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [74]:
def flatten(lst):
    """
    Flattens a nested list into a single-dimensional list.

    Parameters:
        lst (list): A list that may contain nested lists at any depth.

    Returns:
        list: A flat list with all elements in their original order.

    Example:
        >>> flatten([[1, 2], [3, 4], [5]])
        [1, 2, 3, 4, 5]
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

lst = [[1, 2], [3, 4], [5]]
flatten_lst  = flatten(lst)
print(flatten_lst)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [76]:
def access_nested_element(lst,indices):
    """
    Extracts a specific element from a nested list using a sequence of indices.

    Parameters:
        lst (list): A nested list to search through.
        indices (list of int): A list of indices representing the path to the element.

    Returns:
        The element found at the specified position.
    """
    for index in indices:
        lst = lst[index]
    return lst
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1,2]

ele = access_nested_element(lst, indices)
print(ele)


6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
                                                                                     
• Requirements:
                                                                                     
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
                                                                                     
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [78]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
        lst (list): A list that may contain numbers or further nested lists.

    Returns:
        int/float: The total sum of all numeric elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

lst = [[1, 2], [3, [4, 5]], 6]
sum_lst = sum_nested(lst)
print(sum_lst)

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
    
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [79]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list containing elements to filter.
        elem: The element to remove from the list.

    Returns:
        list: The nested list with all occurrences of elem removed.

    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
output = remove_element(lst, elem)
print(output)

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [82]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
        lst (list): A nested list containing numeric values.

    Returns:
        int/float: The largest number found in the nested list.
    """
    values = []
    for item in lst:
        if isinstance(item, list):
            values.append(find_max(item))
        else:
            values.append(item)
    return max(values)

lst = [[1, 2], [3, [4, 5]], 6]
output = find_max(lst)
print(output)

6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.
    
• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
    
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [85]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): A nested list to search through.
        elem: The element to count.

    Returns:
        int: The total number of times elem appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
output = count_occurrences(lst, elem)
print(output)

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
    
• Requirements:
    
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
    
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [86]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single flat list, regardless of depth.

    Parameters:
        lst (list): A list that may contain lists nested at any depth.

    Returns:
        list: A single-dimensional list with all elements in their original order.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(lst)
print(output)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.
    
• Requirements:
    
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
    
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [88]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): A nested list containing numeric values.

    Returns:
        float: The arithmetic mean of all elements in the nested list.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return sum(result)/len(result)

lst = [[1, 2], [3, 4], [5, 6]]
output = average_nested(lst)
print(output)

3.5


# 3. NumPy:

## 3.1 Introduction to Array ndarray:

In [89]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



### NumPy Array - Types:

In [91]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



### 3.1.1 Some of the key attributes of ndarray:

1. .ndim Number of Dimensions: Returns the number of dimensions (axes) in the array.

In [95]:
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


2. .shape Shape of the Array: Returns a tuple representing the size of each dimension.

In [96]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


Shape: (2, 2, 3)

First dimension (2) - How many "pages" or "layers"?

We have 2 pages: [[1,2,3],[4,5,6]] and [[7,8,9],[10,11,12]]


Second dimension (2) - How many "rows" on each page?

Each page has 2 rows: [1,2,3] and [4,5,6] on the first page


Third dimension (3) - How many "columns" in each row?

Each row has 3 numbers: 1, 2, 3

3. .size Total Number of Elements: Returns the total number of elements in the array.

In [97]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


4. .dtype Data Type of Elements: Returns the data type of the array elements.

In [98]:
print(arr_1d.dtype) # Output: int64 (or int32)
arr_float = np.array([1.1, 2.2, 3.3])
print(arr_float.dtype) # Output: float64

int64
float64


5. .itemsize Size of Each Element in Bytes: Returns the size (in bytes) of one array element.

In [99]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


In [100]:
print(arr_float.itemsize)

8


6. .nbytes Total Memory Consumption: Returns the total memory (in bytes) used by the array.

In [101]:
print(arr_1d.nbytes) # Output: 40 (5 elements \times 8 bytes each for int64)

40


7. .T Transpose of the Array: Returns the transposed version of the array.

In [102]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


8. .flat Flattening the Array: Returns an iterator over a 1D representation of the array.

In [109]:
for item in arr_3d.flat:
    print(item, end=" ") 


1 2 3 4 5 6 7 8 9 10 11 12 

9. .real and .imag - Real and Imaginary Parts: Used for complex number arrays.

In [111]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


10. .astype(dtype) Convert Data Type: Converts the array elements to a specified data type.

In [112]:
arr_float = arr_2d.astype(float)
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]]


### 3.1.2 NumPy ndarray - reshape:

In [115]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
print(reshaped_array)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)
[[1 2]
 [3 4]
 [5 6]]


## 3.2 How to Create an Array {ndarray}?

• Using in-built function - Arrays with Evenly spaced values:

– arange: The syntax of arange is arange([start,]stop[,step],[,dtype=None])

In [116]:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


– linspace: The syntax is linpspace(start,stop,num=50,endpoint=True,retstep=False)

In [2]:
import numpy as np
# 50 values between 1 and 10:
print(np.linspace(1, 10))
# 7 values between 1 and 10:
print(np.linspace(1, 10, 7))
# excluding the endpoint:
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [3]:
# With retstep=True
array, step = np.linspace(0, 10, 5, retstep=True)
# Output: array = [ 0.   2.5  5.   7.5 10. ]
# Output: step  = 2.5

Instead of returning only the array of numbers, it returns a tuple containing two items: (the array, the step size). 

False (Default): Returns only the ndarray of evenly spaced samples.

True: Returns a tuple: (ndarray, step), where step is a float representing the distance between adjacent values.

• Creating or Initializing with Ones, Zeros and Empty:

In [121]:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3,4)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[0.00000000e+000 1.32837143e-311]
 [1.32837143e-311 1.32837143e-311]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


• By Manipulating Existing Array:

In [122]:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


– Using shape of an existing array.

In [125]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1.32838403e-311  3.94476225e-103  1.32838535e-311]
 [ 1.32838535e-311  5.43472210e-323  6.91691904e-323]]


• By Combining or joining array:

– Horizontal Stacking: The np.hstack() function stacks arrays horizontally (side by side).
All arrays must have the same number of rows.
    
– Vertical Stacking: The np.vstack() function stacks arrays vertically (on top of each
other). All arrays must have the same number of columns.

In [5]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# here hstack joins the arrays 0s and 1s but we have to consider the number of rows it works in there are same number of rows.
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


– concatenation: np.concatenate((array1, array2), axis=0) joins arrays along a speci-
fied axis.

∗ axis = 0: Concatenate along the rows (vertical stacking).This means the arrays are
stacked on top of each other. The number of columns must match across the arrays.
    
∗ axis = 1: Concatenate along the column (horizontal stacking).This means the arrays
are placed side by side. The number of rows must match across the arrays.
    
∗ axis = 2: Concatenate along the third dimension (depth stacking). This is typically
used for 3D arrays or higher-dimensional arrays, where the number of rows and columns
must match, but new depth layers are added.

In [11]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)

# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (thirddimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


## 3.3 Vectorization:

Vectorization is the process of converting an operation that uses explicit loops into an operation that
uses Numpy’s array operations, which are optimized for performance. Vectorized operations are typically
much faster than their loop-based equivalents.

In [13]:
import numpy as np
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.42830 seconds
Vectorized Execution Time: 0.00336 seconds
Vectorization is approximately 127.39 times faster!


# To - Do - NumPy

## Basic Vector and Matrix Operation with Numpy.

### Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [16]:
emp_arr = np.empty((2,2))
print(emp_arr)

[[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]


2. Initialize an all one array with size 4X2.

In [18]:
ones_arr = np.ones((4,2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [32]:
arr = np.array([1,2,3,4,5])
arr = np.full((arr.shape), 7, arr.dtype)  # np.full(shape, fill_value, dtype)
print(arr)

[7 7 7 7 7]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [33]:
arr = np.array([1,2,3,4,5])
new_arr = np.zeros((arr.shape), arr.dtype)
print(new_arr)

[0 0 0 0 0]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [34]:
ones_arr = np.ones((arr.shape), arr.dtype)
print(ones_arr)

[1 1 1 1 1]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [35]:
new_list = [1,2,3,4]
arr = np.array(new_list)
print(arr)

[1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [36]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [39]:
mat = np.arange(0, 9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [41]:
eye_mat = np.eye(3,3)
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [44]:
arr = np.random.random(30)
print(arr)
mean = arr.mean()
print(mean)

[0.22655373 0.88301711 0.6383028  0.89397818 0.39250149 0.94577063
 0.46888682 0.53289055 0.32897964 0.65358837 0.1645522  0.56306969
 0.60176382 0.41937717 0.46102988 0.37054744 0.83779845 0.34520044
 0.91040225 0.03464662 0.43310029 0.36038086 0.09766975 0.6166077
 0.39895484 0.8151488  0.95157658 0.89236011 0.02688697 0.73801652]
0.5334519900656233


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [51]:
arr = np.random.rand(10,10)
minimum = arr.min()
maximum = arr.max()

print(arr, minimum, maximum, sep="\n \n")

[[0.58713581 0.23996919 0.78958912 0.74334142 0.13584058 0.35829498
  0.56374011 0.73125015 0.61218482 0.17701425]
 [0.39625495 0.16463853 0.8655999  0.41139068 0.93040282 0.90894035
  0.00921046 0.51225807 0.57860449 0.66652751]
 [0.49284659 0.43163066 0.82280121 0.48431004 0.56808185 0.73974181
  0.87469007 0.55426325 0.87917528 0.51383207]
 [0.88548177 0.14343739 0.45270523 0.14452712 0.74638447 0.0191368
  0.70610997 0.29779223 0.71390316 0.08002032]
 [0.19880578 0.3182832  0.90127419 0.54583244 0.45932151 0.0747273
  0.27452559 0.21053373 0.21439017 0.39677996]
 [0.61782725 0.40346283 0.43207001 0.82432183 0.61030103 0.83518586
  0.92636263 0.51712291 0.27821288 0.57667949]
 [0.05226652 0.38846728 0.02759026 0.52103389 0.56911985 0.42086991
  0.64663599 0.73918143 0.75428514 0.8854257 ]
 [0.19623877 0.70370015 0.47493181 0.60075442 0.83585261 0.68980315
  0.23746178 0.65412001 0.73599154 0.42825434]
 [0.80334219 0.83696322 0.14975478 0.56925478 0.81637502 0.04370697
  0.83385536 0

6. Create a zero array of size 10 and replace 5th element with 1.

In [54]:
arr = np.zeros(10)
arr[4] =1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [57]:
arr = [1,2,0,0,4,0]
rev = arr[::-1]
print(rev)

[0, 4, 0, 0, 2, 1]


8. Create a 2d array with 1 on border and 0 inside.

In [68]:
arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [74]:
arr = np.ones((8,8))
arr[::, ::2] =0
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


### Problem - 3: Array Operations:

In [75]:
x = np.array([[1,2],[3,5]]) 
y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) 
w = np.array([11,12]);

1. Add the two array.

In [80]:
add_arr = x+y
print(add_arr)

add_arr1 = np.add(v,w)
print(add_arr1)

[[ 6  8]
 [10 13]]
[20 22]


2. Subtract the two array

In [81]:
sub_arr = np.subtract(v,w)
print(sub_arr)

sub_arr1 = x-y
print(sub_arr1)

[-2 -2]
[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [84]:
mul_arr = np.multiply(x,2)
print(mul_arr)

mul_arr1 = y*3
print(mul_arr1)

[[ 2  4]
 [ 6 10]]
[[15 18]
 [21 24]]


4. Find the square of each element of the array.

In [85]:
sq_x = np.square(x)
print(sq_x)

[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.


In [87]:
v_dot_w = np.dot(v,w)
x_dot_v = np.dot(x,v)
x_dot_y = np.dot(x,y)
print(v_dot_w, x_dot_v, x_dot_y, sep="\n \n")

219
 
[29 77]
 
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.

{Hint:try np.concatenate() or np.vstack() functions

In [91]:
cat1 = np.concatenate((x,y), axis=1)

cat2 = np.vstack((v,w))

print(cat1, cat2, sep="\n \n")

[[1 2 5 6]
 [3 5 7 8]]
 
[[ 9 10]
 [11 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [93]:
cat3 = np.concatenate((x,v))

#raise value error due to mismatch in dimension, as x is 2 dimension array and v is one dimension array.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### Problem - 4: Matrix Operations:


In [97]:
A = np.array([[3,4],[7,8]]) 
B = np.array([[5,3],[2,1]]);

1. Prove A.A−1 = I.

In [100]:
inv_A = np.linalg.inv(A)

result = np.dot(A, inv_A)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [106]:
left_side = np.dot(A,B)
right_side = B @ A

print(np.array_equal(left_side, right_side))

False


3. Prove (AB)T = BTAT.

In [105]:
left_side = np.dot(A,B).T
b_t = B.T
a_t = A.T
right_side = np.dot(b_t, a_t)

print(np.array_equal(left_side, right_side))


True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}


In [109]:
A = np.array([[2,-3,1], [1,-1,2],[3,1,-1]]) # Coefficient matrix A
B = np.array([-1,-3,9])  # Constants matrix B

inv_A = np.linalg.inv(A)

X = np.dot(inv_A, B)

#lets check if AX=B
ver = np.dot(A,X)
print("AX= ",ver)
print("B= ", B)
print(np.array_equal(ver,B))

AX=  [-1. -3.  9.]
B=  [-1 -3  9]
True


### Experiment: How Fast is Numpy?


1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
                        
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [110]:
import numpy as np
import time

In [111]:
size = 1_000_000

# Create data
list1 = list(range(size))
list2 = list(range(size, 2*size))

array1 = np.arange(size)
array2 = np.arange(size, 2*size)

In [112]:
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
list_add_time = end_time - start_time
print(f"Python Lists: {list_add_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
numpy_add_time = end_time - start_time
print(f"NumPy Arrays: {numpy_add_time:.6f} seconds")

print(f"Speedup: {list_add_time/numpy_add_time:.2f}x faster with NumPy")

Python Lists: 0.146843 seconds
NumPy Arrays: 0.003527 seconds
Speedup: 41.63x faster with NumPy


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
                                
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation

In [113]:
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
list_mult_time = end_time - start_time
print(f"Python Lists: {list_mult_time:.6f} seconds")

# Using NumPy Arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
numpy_mult_time = end_time - start_time
print(f"NumPy Arrays: {numpy_mult_time:.6f} seconds")

print(f"Speedup: {list_mult_time/numpy_mult_time:.2f}x faster with NumPy")

Python Lists: 0.187479 seconds
NumPy Arrays: 0.003723 seconds
Speedup: 50.36x faster with NumPy


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
    
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [114]:
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(size)])
end_time = time.time()
list_dot_time = end_time - start_time
print(f"Python Lists: {list_dot_time:.6f} seconds")
print(f"Result: {dot_product_list}")

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
numpy_dot_time = end_time - start_time
print(f"NumPy Arrays: {numpy_dot_time:.6f} seconds")
print(f"Result: {dot_product_array}")

print(f"Speedup: {list_dot_time/numpy_dot_time:.2f}x faster with NumPy")

Python Lists: 0.240222 seconds
Result: 833332333333500000
NumPy Arrays: 0.001400 seconds
Result: 833332333333500000
Speedup: 171.56x faster with NumPy


4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
                                                                                                                       
• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.

Measure and print the time taken for this operation.


In [ ]:
matrix_size = 10
matrix_list1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix_list2 = [[i*j for j in range(matrix_size)] for i in range(matrix_size)]
matrix_array1 = np.random.rand(matrix_size, matrix_size)
matrix_array2 = np.random.rand(matrix_size, matrix_size)
start_time = time.time()
result_matrix = [[0 for _ in range(matrix_size)] for _ in range(matrix_size)]
for i in range(matrix_size):
    for j in range(matrix_size):
        for k in range(matrix_size):
            result_matrix[i][j] += matrix_list1[i][k] * matrix_list2[k][j]
end_time = time.time()
list_matrix_time = end_time - start_time
print(f"Python Lists: {list_matrix_time:.6f} seconds")
# Using NumPy Arrays
start_time = time.time()
result_matrix_array = np.dot(matrix_array1, matrix_array2)
end_time = time.time()
numpy_matrix_time = end_time - start_time
print(f"NumPy Arrays: {numpy_matrix_time:.6f} seconds")
print(f"Speedup: {list_matrix_time/numpy_matrix_time:.2f}x faster with NumPy"),